/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the current platform's texture sharing protocol name. */
export declare function getPlatform(): string
export declare class TextureSender {
  /**
   * Create a new texture sender.
   *
   * - `name`: Sender name visible in Spout/Syphon receivers
   * - `width`: Initial texture width
   * - `height`: Initial texture height
   */
  constructor(name: string, width: number, height: number)
  /**
   * Send a shared texture to Spout (Win) or Syphon (Mac).
   *
   * - `handle`: The native texture handle from Electron's paint event
   *   - Windows: `texture.textureInfo.handle` (DXGI HANDLE as number/BigInt)
   *   - macOS: `texture.textureInfo.handle` (IOSurfaceID as number)
   * - `width`: Texture width (from `textureInfo.codedSize.width`)
   * - `height`: Texture height (from `textureInfo.codedSize.height`)
   */
  send(handle: number, width: number, height: number): void
  /**
   * Send an IOSurface by direct pointer (macOS only).
   * Use this when you have an IOSurfaceRef buffer from Electron's shared texture.
   *
   * - `surface_buffer`: Buffer containing IOSurfaceRef pointer (8 bytes on 64-bit)
   * - `width`: Texture width
   * - `height`: Texture height
   */
  sendSurface(surfaceBuffer: Buffer, width: number, height: number): void
  /**
   * Stop the sender and release resources.
   * After calling this, the sender cannot be reused.
   */
  stop(): void
  /**
   * Send raw RGBA buffer data to Syphon/Spout.
   * Use this for VideoFrame.copyTo() workflow where you have pixel data in a Buffer.
   *
   * - `data`: Buffer containing RGBA pixel data (BGRA format expected)
   * - `width`: Texture width in pixels
   * - `height`: Texture height in pixels
   * - `bytes_per_row`: Optional stride in bytes. Defaults to width * 4 if not provided.
   */
  sendRgbaBuffer(data: Buffer, width: number, height: number, bytesPerRow?: number | undefined | null): void
  /** Get the current platform name. */
  platform(): string
}
